#!/bin/bash

case "${OP_Maintainer},${OP_BRANCH}" in
coolsnowwolf,master)
	AddPackage git other luci-app-usb3disable rufengsuixing
	# AddPackage svn package/kernel mt76 openwrt/openwrt/trunk/package/kernel
;;
esac
