#!/bin/sh
CORES=$(awk -F '[ :]' '/cpu cores/ {print $4;exit}' /proc/cpuinfo)
SENSORS="$(sensors 2>/dev/null | grep 'Core 0')"
if [ "${CORES}" -le 2 ];then
	MHz=$(grep 'MHz' /proc/cpuinfo | cut -c12- | sed -n '1p')
	[ -n "${SENSORS}" ] && TEMP="(+$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}' | cut -d '+' -f2))"
else
	MHz="$(echo "$(grep 'MHz' /proc/cpuinfo | awk '{Freq_Sum += $4};END {print Freq_Sum}') / ${CORES}" | bc)"
	[ -n "${SENSORS}" ] && TEMP="(+$(echo "$(sensors | grep Core | awk '{Sum += $3};END {print Sum}') / ${CORES}" | bc)°C)"
fi
echo "$MHz MHz ${TEMP}"
sleep 1
